package uk.gov.hmrc.test.api.scalatest.tags

import org.scalatest.Tag

// Auto-generated by TagsObjectGenerator. Re-run after spec tags change.

object DTD_1874 extends Tag("DTD_1874")
object DTD_1959 extends Tag("DTD_1959")
object DTD_2140 extends Tag("DTD_2140")
object DTD_2166 extends Tag("DTD_2166")
object DTD_2167 extends Tag("DTD_2167")
object DTD_2168 extends Tag("DTD_2168")
object DTD_2216 extends Tag("DTD_2216")
object DTD_2243 extends Tag("DTD_2243")
object DTD_2244 extends Tag("DTD_2244")
object DTD_2351 extends Tag("DTD_2351")
object DTD_2371 extends Tag("DTD_2371")
object DTD_2714 extends Tag("DTD_2714")
object DTD_2940 extends Tag("DTD_2940")
object DTD_3163 extends Tag("DTD_3163")
object DTD_3180 extends Tag("DTD_3180")
object DTD_3325 extends Tag("DTD_3325")
object DTD_3523 extends Tag("DTD_3523")
object DTD_400 extends Tag("DTD_400")
object DTD_4201 extends Tag("DTD_4201")
object WIP extends Tag("WIP")
